#!/bin/bash
#
# ComfyUI Standalone Installation Script
# Generated by AI Launcher (https://your-site.com)
#
# This script will:
# 1. Set up ComfyUI v0.34.0
# 2. Install 0 custom node(s)
# 3. Download 19 model(s)
# 4. Configure the environment
#
# Usage:
#   1. Set your API tokens below (if needed)
#   2. Run: bash install.sh
#

set -e  # Exit on error


# ===== STEP 1: Parse Command-Line Arguments =====
# This script can accept tokens as command-line arguments or environment variables
# Usage: bash script.sh --hf-token=YOUR_HF_TOKEN --civitai-token=YOUR_CIVITAI_TOKEN

for arg in "$@"; do
    case $arg in
        --hf-token=*)
            export HF_TOKEN="${arg#*=}"
            shift
            ;;
        --civitai-token=*)
            export CIVITAI_TOKEN="${arg#*=}"
            shift
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --hf-token=TOKEN        Set HuggingFace API token"
            echo "  --civitai-token=TOKEN   Set Civitai API token"
            echo "  --help                  Show this help message"
            echo ""
            echo "Example:"
            echo "  bash $0 --hf-token=hf_xxx --civitai-token=abc123"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Validate tokens are set if needed

if [[ -z "$HF_TOKEN" ]]; then
    echo "ERROR: HuggingFace token is required for your model selection"
    echo "Please provide it using: --hf-token=YOUR_TOKEN"
    exit 1
fi

if [[ -z "$CIVITAI_TOKEN" ]]; then
    echo "ERROR: Civitai token is required for your model selection"
    echo "Please provide it using: --civitai-token=YOUR_TOKEN"
    exit 1
fi


# ===== STEP 2: Configuration =====
COMFYUI_DIR=/workspace/ComfyUI
COMFYUI_VERSION="v0.34.0"

# Custom nodes configuration
NODES=(

)

# Model configuration
VAE_MODELS=(
    "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/vae/minimax_h3_audio_vae_fp32.safetensors|minimax_h3_audio_vae_fp32.safetensors"
    "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/vae/minimax_h3_video_vae_fp16.safetensors|minimax_h3_video_vae_fp16.safetensors"
)

TEXT_ENCODERS_MODELS=(
    "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/text_encoders/qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors|qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors"
)

DIFFUSION_MODELS_MODELS=(
    "https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/diffusion_models/minimax_h3_fl2va_bf16.safetensors|minimax_h3_fl2va_bf16.safetensors"
)

LORA_MODELS=(
    "https://civitai.com/api/download/models/3201619|galaxyace_lora_minimax_h3_galaxyace_lora.safetensors"
    "https://civitai.com/api/download/models/3268303|hmnsfw_-_aio_sex_lora_v2_5.safetensors"
    "https://civitai.com/api/download/models/3242184|bouncing_boobs_-_ltx___wan___h3_h3_rev2vid_v0_7.safetensors"
    "https://civitai.com/api/download/models/3220766|h3_-_ltx_2_3_-_i2v_t2v_video_reasoning_lora_vbvr_h3_v1.safetensors"
    "https://civitai.com/api/download/models/3202064|epic_cumshots_h3_alpha.safetensors"
    "https://civitai.com/api/download/models/3245935|boob_physics_minimax_h3___wan2_2_minimax_h3.safetensors"
    "https://civitai.com/api/download/models/3252313|better_titfuck__minimax__wan__hunyuan__v0_5_minimax_h3.safetensors"
    "https://civitai.com/api/download/models/3266628|_mmh3__mystic_xxx_v4_0__fl2va___ref2va_.safetensors"
    "https://civitai.com/api/download/models/2784573|daring_s_deepthroat_h3_ltx2_3_ltxv_2_3_t2v_i2v_v0_1.safetensors"
    "https://civitai.com/api/download/models/3216751|hmbreasts_-_breasts_areoles_lora_for_minimax_h3_v1_0.safetensors"
    "https://civitai.com/api/download/models/3238863|sideview_deepthroat_-_minimax_h3_lora_-_k3nk_minimax_h3_-_v1_0.safetensors"
    "https://civitai.com/api/download/models/3278283|breast_play___jiggle_for_minimax_h3_v2_0.safetensors"
    "https://civitai.com/api/download/models/3255024|h3_ass_jiggle__i2v__fl2va_-_i2v_v1_0.safetensors"
    "https://civitai.com/api/download/models/3282190|h3_jiggle_walk_v1_0.safetensors"
    "https://civitai.com/api/download/models/3201584|icy_twerk_pro_max_v1_0.safetensors"
)

# ===== STEP 3: Helper Functions =====

function print_header() {
    echo ""
    echo "=============================================="
    echo "  ComfyUI Installation & Model Setup"
    echo "=============================================="
    echo ""
    echo "This will take some time depending on your"
    echo "internet speed and the number of models."
    echo ""
}

function print_end() {
    echo ""
    echo "=============================================="
    echo "  Installation Complete!"
    echo "=============================================="
    echo ""
    echo "You can now start ComfyUI from: $COMFYUI_DIR"
    echo ""
}

function setup_comfyui() {
    echo "Setting up ComfyUI..."

    if [[ -d "$COMFYUI_DIR" ]]; then
        echo "ComfyUI directory exists. Updating to version $COMFYUI_VERSION..."
        cd "$COMFYUI_DIR"

        git config --global --add safe.directory "$COMFYUI_DIR" || true
        git fetch --all --tags || echo "Warning: Could not fetch updates"

        if git checkout "$COMFYUI_VERSION" 2>/dev/null; then
            echo "Successfully checked out $COMFYUI_VERSION"
        else
            echo "Warning: Could not checkout $COMFYUI_VERSION, using current version"
        fi
    else
        echo "Cloning ComfyUI repository..."
        git clone https://github.com/comfyanonymous/ComfyUI.git "$COMFYUI_DIR"
        cd "$COMFYUI_DIR"

        if git checkout "$COMFYUI_VERSION" 2>/dev/null; then
            echo "Successfully checked out $COMFYUI_VERSION"
        fi
    fi

    # Install requirements
    if [[ -f "requirements.txt" ]]; then
        echo "Installing ComfyUI requirements..."
        pip install --no-cache-dir -r requirements.txt
    fi
}

function install_custom_nodes() {
    if [[ ${#NODES[@]} -eq 0 ]]; then
        echo "No custom nodes to install."
        return
    fi

    echo "Installing ${#NODES[@]} custom node(s)..."

    for repo in "${NODES[@]}"; do
        dir="${repo##*/}"
        path="${COMFYUI_DIR}/custom_nodes/${dir}"

        if [[ -d $path ]]; then
            echo "Updating node: $repo"
            (cd "$path" && git pull)
        else
            echo "Installing node: $repo"
            git clone "$repo" "$path" --recursive
        fi

        # Install requirements if they exist
        if [[ -f "$path/requirements.txt" ]]; then
            pip install --no-cache-dir -r "$path/requirements.txt"
        fi
    done
}

function download_file() {
    local url_input="$1"
    local download_dir="$2"
    local custom_filename=""
    local download_url=""

    # Parse URL and custom filename if provided in format "URL|FILENAME"
    if [[ "$url_input" == *"|"* ]]; then
        download_url="${url_input%|*}"
        custom_filename="${url_input#*|}"
        custom_filename="$(echo "$custom_filename" | sed 's/\//_/g')"
    else
        download_url="$url_input"
    fi

    # Fix Hugging Face blob URLs
    if [[ $download_url =~ ^https://([a-zA-Z0-9_-]+\.)?huggingface\.co.*\/blob\/ ]]; then
        download_url=$(echo "$download_url" | sed 's|/blob/|/resolve/|')
    fi

    mkdir -p "$download_dir"

    # Download with appropriate auth
    if [[ -n $HF_TOKEN && $download_url =~ ^https://([a-zA-Z0-9_-]+\.)?huggingface\.co ]]; then
        if [[ -n "$custom_filename" ]]; then
            wget --header="Authorization: Bearer $HF_TOKEN" -nc --show-progress -O "$download_dir/$custom_filename" "$download_url"
        else
            wget --header="Authorization: Bearer $HF_TOKEN" -nc --content-disposition --show-progress -P "$download_dir" "$download_url"
        fi
    elif [[ -n $CIVITAI_TOKEN && $download_url =~ ^https://([a-zA-Z0-9_-]+\.)?civitai\.com ]]; then
        # Append token as query parameter for Civitai (more reliable than header)
        local civitai_url="$download_url"
        if [[ "$civitai_url" == *"?"* ]]; then
            civitai_url="${civitai_url}&token=$CIVITAI_TOKEN"
        else
            civitai_url="${civitai_url}?token=$CIVITAI_TOKEN"
        fi
        if [[ -n "$custom_filename" ]]; then
            curl -fL -o "$download_dir/$custom_filename" "$civitai_url"
        else
            (cd "$download_dir" && curl -fL -J -O "$civitai_url")
        fi
    else
        if [[ -n "$custom_filename" ]]; then
            wget -nc --show-progress -O "$download_dir/$custom_filename" "$download_url"
        else
            wget -nc --content-disposition --show-progress -P "$download_dir" "$download_url"
        fi
    fi
}

function download_models() {
    local dir="$1"
    shift
    local arr=("$@")

    if [[ ${#arr[@]} -eq 0 ]]; then
        return
    fi

    echo "Downloading ${#arr[@]} model(s) to $dir..."

    for url in "${arr[@]}"; do
        echo "Downloading: $url"
        download_file "$url" "$dir"
    done
}

# ===== STEP 4: Main Installation =====

print_header

echo "Step 1/3: Setting up ComfyUI..."
setup_comfyui

echo ""
echo "Step 2/3: Installing custom nodes..."
install_custom_nodes

echo ""
echo "Step 3/3: Downloading models..."
    download_models \
        "${COMFYUI_DIR}/models/vae" \
        "${VAE_MODELS[@]}"
    download_models \
        "${COMFYUI_DIR}/models/text_encoders" \
        "${TEXT_ENCODERS_MODELS[@]}"
    download_models \
        "${COMFYUI_DIR}/models/diffusion_models" \
        "${DIFFUSION_MODELS_MODELS[@]}"
    download_models \
        "${COMFYUI_DIR}/models/loras" \
        "${LORA_MODELS[@]}"

print_end
